version: '3.8'
services:
  dynamodb-local-bot:
    command: "-jar DynamoDBLocal.jar -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local-bot
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    environment:
      - LANG=en_US.UTF-8
      - locale-gen=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
  clash-bot-discord-bot-service-data-setup:
    image: "poss11111/clash-bot-service:test"
    command: "node integration/integration-setup.js"
    container_name: clash-bot-discord-bot-service-data-setup
    environment:
      - INTEGRATION_TEST=true
      - HOST=dynamodb-local-bot
  clash-bot-service-bot:
    image: "poss11111/clash-bot-service:test"
    container_name: clash-bot-service-bot
    ports:
      - "0.0.0.0:80:80"
    environment:
      - INTEGRATION_TEST=true
      - HOST=dynamodb-local-bot
