module.exports = {
    Champions: require('./champions'),
    Dance: require('./dance'),
    Help: require('./help'),
    JoinTeamByName: require('./join-team-by-name'),
    NewTeam: require('./new-team'),
    Ping: require('./ping'),
    Register: require('./register'),
    Subscribe: require('./subscribe'),
    SuggestChampion: require('./suggest-champion'),
    Teams: require('./teams'),
    Tentative: require('./tentative'),
    Time: require('./time'),
    Unregister: require('./unregister'),
    Unsubscribe: require('./unsubscribe'),
};
