version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    environment:
      - LANG=en_US.UTF-8
      - locale-gen=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
  dynamodb-local-gui:
    image: 'aaronshaf/dynamodb-admin:latest'
    container_name: dynamodb-local-gui
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
  clash-bot-service-data-setup:
    image: 'poss11111/clash-bot-webapp-service:test'
    command: "node integration/integration-setup.js"
    container_name: clash-bot-service-data-setup
    environment:
      - INTEGRATION_TEST=true
      - HOST=dynamodb-local
  clash-bot-local-service:
    image: 'poss11111/clash-bot-webapp-service:test'
    container_name: clash-bot-webapp-service
    ports:
      - "80:80"
    environment:
      - INTEGRATION_TEST=true
      - HOST=dynamodb-local-test
      - WS_SERVICE_HOSTNAME=ws://clash-bot-ws-service:8081
      - PORT=80
      - LOGGER_LEVEL=info
